"""fix cyclic fk between seismic_events and shakemap_jobs

Revision ID: 6a88a6aac134
Revises: f4cd0c27a962
Create Date: 2026-04-23 12:52:16.013828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a88a6aac134'
down_revision = 'f4cd0c27a962'
branch_labels = None
depends_on = None


def upgrade():

    # 🔥 STEP 1 — parent table first
    with op.batch_alter_table('seismic_events', schema=None) as batch_op:
        batch_op.alter_column(
            'seiscomp_oid',
            existing_type=mysql.VARCHAR(length=50),
            nullable=False
        )
        batch_op.create_index(
            'ix_seismic_events_seiscomp_oid',
            ['seiscomp_oid'],
            unique=True   # 🔥 აუცილებელია FK-სთვის
        )
        batch_op.drop_column('shakemap_status')

    # 🔥 STEP 2 — child table მერე
    op.create_table(
        'shakemap_jobs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('celery_task_id', sa.String(length=128), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('seiscomp_oid', sa.String(length=50), nullable=False),
        sa.Column('uuid', sa.String(length=255), nullable=False),

        sa.ForeignKeyConstraint(
            ['seiscomp_oid'],
            ['seismic_events.seiscomp_oid'],
            name='fk_shakemap_jobs_event_oid'
        ),
        sa.ForeignKeyConstraint(
            ['uuid'],
            ['users.uuid'],
            name='fk_shakemap_jobs_user_uuid'
        ),

        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('celery_task_id')
    )

    with op.batch_alter_table('shakemap_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_shakemap_jobs_seiscomp_oid', ['seiscomp_oid'], unique=False)
        batch_op.create_index('ix_shakemap_jobs_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seismic_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shakemap_status', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_index(batch_op.f('ix_seismic_events_seiscomp_oid'))
        batch_op.alter_column('seiscomp_oid',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('shakemap_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shakemap_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_shakemap_jobs_seiscomp_oid'))

    op.drop_table('shakemap_jobs')
    # ### end Alembic commands ###
