"""sync check

Revision ID: 86bf7467a12b
Revises: 27ee29ca94ce
Create Date: 2026-06-12 09:19:37.395257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86bf7467a12b'
down_revision = '27ee29ca94ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seismic_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ux_seismic_events_event_id'))
        batch_op.drop_index(batch_op.f('ix_seismic_events_seiscomp_oid'))
        batch_op.create_index(batch_op.f('ix_seismic_events_seiscomp_oid'), ['seiscomp_oid'], unique=False)
        batch_op.create_index(batch_op.f('ix_seismic_events_event_id'), ['event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seismic_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seismic_events_event_id'))
        batch_op.drop_index(batch_op.f('ix_seismic_events_seiscomp_oid'))
        batch_op.create_index(batch_op.f('ix_seismic_events_seiscomp_oid'), ['seiscomp_oid'], unique=True)
        batch_op.create_index(batch_op.f('ux_seismic_events_event_id'), ['event_id'], unique=True)

    # ### end Alembic commands ###
