"""clean seismic_event

Revision ID: a5376d39b7e8
Revises: 66d33d38b97d
Create Date: 2026-05-21 11:59:51.063991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5376d39b7e8'
down_revision = '66d33d38b97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seismic_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seismic_events_seiscomp_oid'))
        batch_op.create_index(batch_op.f('ix_seismic_events_seiscomp_oid'), ['seiscomp_oid'], unique=False)
        batch_op.drop_column('region_en')
        batch_op.drop_column('region_ge')

    with op.batch_alter_table('shakemap_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shakemap_jobs_seiscomp_oid'))
        batch_op.create_index(batch_op.f('ix_shakemap_jobs_seiscomp_oid'), ['seiscomp_oid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shakemap_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shakemap_jobs_seiscomp_oid'))
        batch_op.create_index(batch_op.f('ix_shakemap_jobs_seiscomp_oid'), ['seiscomp_oid'], unique=False)

    with op.batch_alter_table('seismic_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region_ge', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('region_en', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_index(batch_op.f('ix_seismic_events_seiscomp_oid'))
        batch_op.create_index(batch_op.f('ix_seismic_events_seiscomp_oid'), ['seiscomp_oid'], unique=True)

    # ### end Alembic commands ###
