"""Add new columns to seismic_event

Revision ID: bce39db0df04
Revises: 86bf7467a12b
Create Date: 2026-07-09 08:45:05.696279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce39db0df04'
down_revision = '86bf7467a12b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('published_earthquakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seiscomp_oid', sa.String(length=20), nullable=False),
    sa.Column('wp_response', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['seiscomp_oid'], ['seismic_events.seiscomp_oid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('published_earthquakes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_published_earthquakes_seiscomp_oid'), ['seiscomp_oid'], unique=True)

    op.create_table('send_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seiscomp_oid', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['seiscomp_oid'], ['seismic_events.seiscomp_oid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('send_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_send_notifications_seiscomp_oid'), ['seiscomp_oid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('send_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_send_notifications_seiscomp_oid'))

    op.drop_table('send_notifications')
    with op.batch_alter_table('published_earthquakes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_published_earthquakes_seiscomp_oid'))

    op.drop_table('published_earthquakes')
    # ### end Alembic commands ###
