"""create user table

Revision ID: f4cd0c27a962
Revises: 
Create Date: 2026-04-23 07:10:50.670313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4cd0c27a962'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seismic_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shakemap_status', sa.String(length=20), nullable=False))
        batch_op.drop_column('shakemap_calculated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seismic_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shakemap_calculated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_column('shakemap_status')

    # ### end Alembic commands ###
